In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

plt.rcParams.update({
    "text.usetex": True,
    "font.family": "Helvetica"
})

import matplotlib as mpl

In [2]:
import sys
from os.path import dirname

sys.path.append(dirname("../src/"))

In [3]:
from samosa.lattice import Lattice

In [4]:
lat = Lattice(dimension=3, space_group_index=194)

In [5]:
print(lat.space_group)

Symmetry group 194

Generators:
[[ 0. -1.  0.]
 [ 1. -1.  0.]
 [ 0.  0.  1.]], [0. 0. 0.]

[[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0.  1.]], [0.  0.  0.5]

[[ 0.  1.  0.]
 [ 1.  0.  0.]
 [ 0.  0. -1.]], [0. 0. 0.]

[[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]], [0. 0. 0.];

Group order: 24;


In [7]:
print(lat.wyckoff_list[0].point_group(as_permutations=False))

Generators:
[[ 0. -1.  0.]
 [ 1. -1.  0.]
 [ 0.  0.  1.]]

[[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0.  1.]]

[[ 0.  1.  0.]
 [ 1.  0.  0.]
 [ 0.  0. -1.]]

[[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]];


In [11]:
print(lat)

Lattice object.

Lattice type: Hexagonal_P;
Crystallographic point group: D6h;
Space group index (ITC vol.A): 194;


In [6]:
from samosa.database import SpaceGroupDatabase
from samosa.symmetry.point_group_utils import *

In [7]:
test_2 = SpaceGroupDatabase()
test_2

SpaceGroupDatabase(file_list = ['space_group_lattices.toml', 'space_group_generators.toml'])

In [8]:
print(test_2)

Database object containing files space_group_lattices.toml, space_group_generators.toml


In [9]:
test_2.space_group_generators[(3, 194)]

[[[1.0, 0.0, 0.0, 0.0], [0.0, 1.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0.0]],
 [[0.0, -1.0, 0.0, 0.0], [1.0, -1.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0.0]],
 [[-1.0, 0.0, 0.0, 0.0], [0.0, -1.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0.5]],
 [[0.0, 1.0, 0.0, 0.0], [1.0, 0.0, 0.0, 0.0], [0.0, 0.0, -1.0, 0.0]],
 [[-1.0, 0.0, 0.0, 0.0], [0.0, -1.0, 0.0, 0.0], [0.0, 0.0, -1.0, 0.0]]]

In [10]:
test_2.available_files

[PosixPath('/home/azelenskiy/Documents/samosa/tutorials/../src/samosa/database/symmetry_operations.toml'),
 PosixPath('/home/azelenskiy/Documents/samosa/tutorials/../src/samosa/database/space_group_generators.toml'),
 PosixPath('/home/azelenskiy/Documents/samosa/tutorials/../src/samosa/database/point_groups.toml'),
 PosixPath('/home/azelenskiy/Documents/samosa/tutorials/../src/samosa/database/space_group_lattices.toml'),
 PosixPath('/home/azelenskiy/Documents/samosa/tutorials/../src/samosa/database/crystallographic_point_groups.toml')]

In [11]:
test_2.load_file(0)

In [12]:
test_2.data['symmetry_operations.toml']

{'000': {'E': [[1, 0, 0], [0, 1, 0], [0, 0, 1]],
  'I': [[-1, 0, 0], [0, -1, 0], [0, 0, -1]]},
 '100': {'C2': [[1, 0, 0], [0, -1, 0], [0, 0, -1]],
  'C2_H': [[1, -1, 0], [0, -1, 0], [0, 0, -1]],
  'C4p': [[1, 0, 0], [0, 0, 1], [0, -1, 0]],
  'C4m': [[1, 0, 0], [0, 0, -1], [0, 1, 0]],
  'm': [[-1, 0, 0], [0, 1, 0], [0, 0, 1]],
  'm_H': [[-1, 1, 0], [0, 1, 0], [0, 0, 1]],
  'S4m': [[-1, 0, 0], [0, 0, -1], [0, 1, 0]],
  'S4p': [[-1, 0, 0], [0, 0, 1], [0, -1, 0]]},
 '010': {'C2': [[-1, 0, 0], [0, 1, 0], [0, 0, -1]],
  'C2_H': [[-1, 0, 0], [-1, 1, 0], [0, 0, -1]],
  'C4p': [[0, 0, -1], [0, 1, 0], [1, 0, 0]],
  'C4m': [[0, 0, 1], [0, 1, 0], [-1, 0, 0]],
  'm': [[1, 0, 0], [0, -1, 0], [0, 0, 1]],
  'm_H': [[1, 0, 0], [1, -1, 0], [0, 0, 1]],
  'S4m': [[0, 0, 1], [0, -1, 0], [-1, 0, 0]],
  'S4p': [[0, 0, -1], [0, -1, 0], [1, 0, 0]]},
 '001': {'C2': [[-1, 0, 0], [0, -1, 0], [0, 0, 1]],
  'C3p_H': [[0, -1, 0], [1, -1, 0], [0, 0, 1]],
  'C3m_H': [[-1, 1, 0], [-1, 0, 0], [0, 0, 1]],
  'C4p': [[0, -

In [13]:
operator_to_symbol(np.array(test_2.space_group_generators[(3, 194)][1])[:,:-1], as_dict=True)

{'type': 'C', 'n': 3, 'k': 1, 'axis': array([0, 0, 1])}

In [15]:
operator_to_symbol(operator_C([0,0,1], 5).dot(operator_C([0,0,1], 5)), as_dict=True)

{'type': 'C', 'n': 5, 'k': 2, 'axis': array([0, 0, 1])}

In [37]:
from fractions import Fraction
from decimal import Decimal

In [52]:
Fraction(173/254).limit_denominator()

Fraction(173, 254)

In [ ]:
operator_to_symbol()

In [13]:
test_2.lattice_reference['Cubic_P']

{'dimension': 3,
 'T': [195, 198],
 'Th': [200, 201, 205],
 'O': [207, 208, 212, 213],
 'Td': [215, 218],
 'Oh': [221, 222, 223, 224]}

In [27]:
print(test_2.find_space_group(dimension = 3,
                              lattice_type='Cubic_I',
                              point_group_symbol='Oh',
                              as_str=True))

The allowed space groups for lattice type Cubic_I and point group Oh are:
229  230  


In [15]:
print(test_2.allowed_groups('Cubic_P',as_str=True))

The allowed point groups for lattice type Cubic_P are:
T with space groups 195  198  
Th with space groups 200  201  205  
O with space groups 207  208  212  213  
Td with space groups 215  218  
Oh with space groups 221  222  223  224  



In [16]:
print(test_2.allowed_groups('Cubic_P','Oh',as_str=True))

The allowed space groups for lattice type Cubic_P and point group Oh are:
221  222  223  224  


In [20]:
print(test_2.allowed_groups(None,'Oh',as_str=True)[2])

The allowed lattice types for point group Oh are:
Cubic_P with space groups (3, 222)  
Cubic_F with space groups (3, 226)  
Cubic_I with space groups (3, 230)  



In [22]:
a = "{dim}"
a.format(dim=2)

'2'

In [18]:
test_2.n_space_groups[4]

KeyError: 4

In [14]:
tuple(int(i) for i in '2,12'.split(','))

(2, 12)

In [160]:
import toml
import warnings
import pandas as pd

def custom_formatwarning(msg, *args, **kwargs):
    # ignore everything except the message
    return str(msg) + '\n'

warnings.formatwarning = custom_formatwarning

## Tools for lattice generation

__Desired properties:__

* Adjacency methods for nearest-neighbours along the principle lattice directions
* Vertex point group
* Bond point group

In [302]:
lattice_lib = toml.load('../../include/lattices.toml')

In [303]:
point_group_lib = toml.load('../../include/point_groups.toml')

In [304]:
# Create a library that connects lattice point groups to lattices and space 
# groups

point_group_names = point_group_lib.keys()
lib_entries = [{'generators':[],
                'lattices':[],
                'space_groups':[]} for i in range(len(point_group_names))]
                        
crystal_symmetry_lib = dict(zip(point_group_names,lib_entries))

## Assign the point group generators
for pg in point_group_names:
    crystal_symmetry_lib[pg]['generators'] = point_group_lib[pg]['generators']

## Assign possible bravais lattices and space groups
lattice_names = lattice_lib.keys()

for l in lattice_names:
    allowed_pg = list(lattice_lib[l].keys())[1:]
    for pg in allowed_pg:
        crystal_symmetry_lib[pg]['lattices'] += [l]
        crystal_symmetry_lib[pg]['space_groups'] += lattice_lib[l][pg]['space_groups']

In [280]:
# Create a library that provides lattice type and point group symmetry from the
# space group number

space_group_names = np.arange(-17,230)
space_group_names[17:] += 1

lib_entries = [{'lattice':'',
                'point_group':''} for i in range(len(space_group_names))]

space_group_lib = dict(zip(space_group_names,lib_entries))

for l in lattice_names:
    allowed_pg = list(lattice_lib[l].keys())[1:]
    for pg in allowed_pg:
        allowed_sg = lattice_lib[l][pg]['space_groups']
        for sg in allowed_sg:
            space_group_lib[sg]['lattice'] = l
            space_group_lib[sg]['point_group'] = pg

In [305]:
class lattice:
    """
    Defines the properties of a periodic system. 
    The properies of a lattice object are

    n_sites         - int, total number of sites in the system;
    bravais_lattice - str, name of the Bravais lattice;
    basis_size      - int, number of basis vectors or the dimensionality of the 
                           lattice. Supported 1-3 for conventional lattices;
    l_array         - list or np.ndarray, for basis_size != 1, the dimensions
                                          of the lattice along the principle 
                                          directions; 
    
    """

    bravais_lattice = None
    point_group = None
    
    def __init__(self, dimensions, bravais_lattice = None, point_group = None):

        ## Assign lattice dimensions 
        dimensions_type = type(dimensions)
        
        if dimensions_type == np.ndarray or dimensions_type == list:
            dimensions_l = len(dimensions)
            
            self.n_sites = np.prod(dimensions)
            self.l_array = dimensions

        # If given a single integer, assign the total number of sites, raise
        # error for 2- and 3-dimensional lattices
        elif dimensions_type == int:
            if self.basis_size != 1:    
                raise TypeError('dimensions must be a list or np.ndarray '\
                              + 'of size {}'.format(self.basis_size)\
                              + ', not int')
                
            self.n_sites = dimensions

        else:
            raise TypeError('dimensions must be of type int, list, '\
                          + 'or np.ndarray, not ' + dimensions_type.__name__)

        ## Specify bravais lattice type, point group symmetry, and
        ## dimensionality of the lattice
        if bravais_lattice != None:
            self.set_lattice_type(bravais_lattice)
    
            ## Specify the lattice point group
            if point_group != None:
                self.set_point_group(point_group)

            else:
                point_group_list = lattice_lib[self.bravais_lattice].keys()
                point_group_list = list(point_group_list)[1:]
                supported_pg_names = ", ".join(point_group_list)
                
                warnings.warn('Point group not selected!'\
                            + '\nAllowed point groups are: ' + supported_pg_names)

        else:
            ## Specify the lattice point group
            if point_group != None:
                self.set_point_group(point_group)

                lattice_list = crystal_symmetry_lib[point_group]['lattices']
                supported_names = ", ".join(lattice_list)
                
                warnings.warn('Lattice type not selected!'\
                              '\nAllowed Bravais lattices are: '\
                            + supported_names + \
                              '\nSetting dimensionality to the size of'
                              ' the dimensions array')

            else:
                point_group_list = crystal_symmetry_lib.keys()
                point_group_list = list(point_group_list)
                supported_pg_names = ", ".join(point_group_list)

                warnings.warn('Lattice type not selected!'\
                              '\nSetting dimensionality to the size of'
                              ' the dimensions array')
                warnings.warn('Point group not selected!')

            self.basis_size = len(dimensions)


    def set_lattice_type(self, bravais_lattice):
        """
        Assigns lattice properties depending on the name of the Bravais lattice

        Arguments:

        bravais_lattice - str, name of the Bravais lattice.
        """

        if self.TestPointGroupSet():  
            lattice_list = crystal_symmetry_lib[self.point_group]['lattices']
            
            if bravais_lattice not in lattice_list:
                supported_names = ", ".join(lattice_list)
                raise NameError('Bravais lattice name must be one of: '\
                              + lattice_names)
        
        # Test if the new lattice properties match up with the existing ones
        bravais_lattice_new = bravais_lattice
        self.TestLatticeType(bravais_lattice_new)
        
        basis_size_new = lattice_lib[bravais_lattice]['dimension']
        self.TestLatticeDimensions(basis_size_new)

        # Record the new lattice name dimensionality
        self.bravais_lattice = bravais_lattice_new
        self.basis_size = basis_size_new

    def set_point_group(self, point_group):
        """
        Assigns point group based on the Bravais lattice type

        Arguments:

        point_group - str, name of the point group.
        """

        if self.TestLatticeSet():
            point_group_list = lattice_lib[self.bravais_lattice].keys()
            point_group_list = list(point_group_list)[1:]
            
            if point_group not in point_group_list:
                supported_pg_names = ", ".join(point_group_list)
                raise NameError('Point group must be one of: '\
                              + supported_pg_names)

        # Record the new lattice point group
        self.point_group = point_group

    
    def TestLatticeSet(self):
        """
        Check that the lattice type is selected
        """
        if self.bravais_lattice == None:
            return False
        else:
            return True

    def TestPointGroupSet(self):
        """
        Check that the point group is selected
        """
        if self.point_group == None:
            return False
        else:
            return True
    
    def TestLatticeType(self,bravais_lattice):
        """
        Check that the lattice type is one of the implemented lattices
        """
        if bravais_lattice not in lattice_lib.keys():
            supported_names = ", ".join(lattice_lib.keys())
            raise NameError('Incorrect lattice name: ' + bravais_lattice\
                          + '\nSupported lattices: ' + supported_names)
    
    def TestLatticeDimensions(self,basis_size):
        """
        Check that the l_array is of the right size and matches 
        the total number of sites
        """
        if len(self.l_array) != basis_size:
            raise TypeError('l_array has dimension '\
                          + '{}'.format(len(self.l_array))\
                          + ' but must be of dimension '\
                          + '{}'.format(basis_size))

        if np.prod(self.l_array) != self.n_sites:
            raise ValueError('Lattice dimensions in l_array do not sum to '\
                           + 'n_sites!')
    
    
    def __str__(self):

        base_string = 'Lattice object with {} sites'.format(self.n_sites)

        base_string += '\nDimension: {}'.format(self.basis_size)

        if self.basis_size == 2:
            base_string += '\nL1 = {}'.format(self.l_array[0])
            base_string += ', L2 = {}'.format(self.l_array[1])
        
        elif self.basis_size == 3:
            base_string += '\nL1 = {}'.format(self.l_array[0])
            base_string += ', L2 = {}'.format(self.l_array[1])
            base_string += ', L3 = {}'.format(self.l_array[2])
        
        if self.bravais_lattice != None:
            base_string += '\nBravais_lattice type: ' + self.bravais_lattice

        if self.point_group != None:
            base_string += '\nCrystal point group: ' + self.point_group
            
        return base_string

In [301]:
new_lattice = lattice([2,3],bravais_lattice='hexagonal_p',point_group='C3')

print(new_lattice)

Lattice object with 6 sites
Dimension: 2
L1 = 2, L2 = 3
Bravais_lattice type: hexagonal_p
Crystal point group: C3


In [78]:
type([0])

list

In [ ]:
from samosa.database