In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt


plt.rcParams.update({
    "text.usetex": True,
    "font.family": "Helvetica"
})

import matplotlib as mpl

In [2]:
import sys
from os.path import dirname

sys.path.append(dirname("../src/"))

import samosa.symmetry.group_utils as g_utils
import samosa.symmetry.point_group_utils as pg_utils

In [3]:
oh_group = pg_utils.point_group('Oh')

In [4]:
print(oh_group)

Symmetry group Oh

Generators:
[[-0. -1. -0.]
 [-0. -0. -1.]
 [-1. -0. -0.]]
[[ 0. -1.  0.]
 [ 1.  0.  0.]
 [ 0.  0. -1.]];

Group order: 48;


In [6]:
oh_group.calculate_elements()

AttributeError: 'MatrixGroupElement' object has no attribute 'dim'

In [5]:
point_o,point_g,point_t,point_s = oh_group.calculate_orbit([1,0,0])

In [6]:
oh_group.generators

[MatrixGroupElement(operator = array([[-0., -1., -0.],
        [-0., -0., -1.],
        [-1., -0., -0.]])),
 MatrixGroupElement(operator = array([[ 0., -1.,  0.],
        [ 1.,  0.,  0.],
        [ 0.,  0., -1.]]))]

In [7]:
point_o

[[1, 0, 0],
 array([ 0.,  0., -1.]),
 array([0., 1., 0.]),
 array([0., 0., 1.]),
 array([-1.,  0.,  0.]),
 array([ 0., -1.,  0.])]

In [8]:
point_g

[PermutationGroupElement(permutation = (1, 2, 4, 5, 3, 0)),
 PermutationGroupElement(permutation = (2, 3, 4, 1, 5, 0))]

In [9]:
point_t[(0,0,-1)]

MatrixGroupElement(operator = array([[-0., -1., -0.],
       [-0., -0., -1.],
       [-1., -0., -0.]]))

In [10]:
for p in point_o:
    print(oh_group.generators[1] * p)

[0. 1. 0.]
[0. 0. 1.]
[-1.  0.  0.]
[ 0.  0. -1.]
[ 0. -1.  0.]
[1. 0. 0.]


In [11]:
point_s

[IdentityGroupElement,
 MatrixGroupElement(operator = array([[ 1.,  0.,  0.],
        [ 0.,  0., -1.],
        [ 0., -1.,  0.]])),
 MatrixGroupElement(operator = array([[ 1.,  0.,  0.],
        [ 0.,  0.,  1.],
        [ 0., -1.,  0.]])),
 MatrixGroupElement(operator = array([[ 1.,  0.,  0.],
        [ 0., -1.,  0.],
        [ 0.,  0., -1.]])),
 MatrixGroupElement(operator = array([[ 1.,  0.,  0.],
        [ 0.,  1.,  0.],
        [ 0.,  0., -1.]])),
 MatrixGroupElement(operator = array([[ 1.,  0.,  0.],
        [ 0.,  0., -1.],
        [ 0.,  1.,  0.]]))]

In [12]:
oh_perm = g_utils.Group(point_g)

In [12]:
out = oh_perm.calculate_orbit(0)

In [13]:
out[2]

{0: IdentityGroupElement,
 1: PermutationGroupElement(permutation = (1, 2, 4, 5, 3, 0)),
 2: PermutationGroupElement(permutation = (2, 3, 4, 1, 5, 0)),
 3: PermutationGroupElement(permutation = (3, 4, 5, 0, 1, 2)),
 4: PermutationGroupElement(permutation = (4, 5, 3, 2, 0, 1)),
 5: PermutationGroupElement(permutation = (5, 3, 0, 1, 2, 4))}

In [14]:
out[2][3]

PermutationGroupElement(permutation = (3, 4, 5, 0, 1, 2))

In [15]:
out[3][2].inv()

PermutationGroupElement(permutation = (0, 2, 3, 5, 4, 1))

In [16]:
g_utils.Group(out[-1],filter_generators=True)

Group(generators = [PermutationGroupElement(permutation = (0, 2, 1, 5, 4, 3)), PermutationGroupElement(permutation = (0, 5, 1, 2, 4, 3))])

In [9]:
g_utils.Group(point_s,filter_generators=True)

Group(generators = [MatrixGroupElement(operator = array([[ 1.,  0.,  0.],
       [ 0.,  0., -1.],
       [ 0., -1.,  0.]])), MatrixGroupElement(operator = array([[ 1.,  0.,  0.],
       [ 0.,  0.,  1.],
       [ 0., -1.,  0.]]))])

In [12]:
test_o,test_g,test_t,test_s = pg_test.calculate_orbit([1,0,0],as_pointer=True)

In [13]:
test_o

[array([1, 0, 0]),
 array([0., 1., 0.]),
 array([-1.,  0.,  0.]),
 array([ 0., -1.,  0.])]

In [14]:
test_g

[PermutationGroupElement(permutation = (1, 2, 3, 0)),
 PermutationGroupElement(permutation = (0, 3, 2, 1))]

In [15]:
test_t

{(1, 0, 0): PointerGroupElement(pointer = []),
 (0.0, 1.0, 0.0): PointerGroupElement(pointer = [(0, 1)]),
 (-1.0, 0.0, 0.0): PointerGroupElement(pointer = [(0, 2)]),
 (0.0, -1.0, 0.0): PointerGroupElement(pointer = [(1, 1), (0, 1)])}

In [16]:
test_s

[PointerGroupElement(pointer = []),
 PointerGroupElement(pointer = [(1, 1)]),
 PointerGroupElement(pointer = [(1, 1), (0, 2)]),
 PointerGroupElement(pointer = [(0, 2), (1, 1), (0, 2)]),
 PointerGroupElement(pointer = [(0, 1), (1, 1), (0, 1)])]

In [17]:
test_s[1]*test_s[1]

PointerGroupElement(pointer = [])

In [13]:
tuple(np.arange(6))

(0, 1, 2, 3, 4, 5)

In [22]:
pg_test.generators += [pg_test.generators[0]*pg_test.generators[1]]
pg_test.generators

[MatrixGroupElement(operator = array([[ 0., -1.,  0.],
        [ 1.,  0.,  0.],
        [ 0.,  0.,  1.]])),
 MatrixGroupElement(operator = array([[ 1., -0., -0.],
        [-0., -1., -0.],
        [ 0., -0.,  1.]])),
 MatrixGroupElement(operator = array([[0., 1., 0.],
        [1., 0., 0.],
        [0., 0., 1.]])),
 MatrixGroupElement(operator = array([[0., 1., 0.],
        [1., 0., 0.],
        [0., 0., 1.]]))]

In [23]:
pg_test.generator_filter()

In [24]:
pg_test.generators

[MatrixGroupElement(operator = array([[ 0., -1.,  0.],
        [ 1.,  0.,  0.],
        [ 0.,  0.,  1.]])),
 MatrixGroupElement(operator = array([[ 1., -0., -0.],
        [-0., -1., -0.],
        [ 0., -0.,  1.]]))]

In [29]:
test_s[-1]

PointerGroupElement(pointer = [(0, 3), (0, 1)])

In [26]:
array_type = (np.ndarray,list,tuple)
array_type_print = [str(a.__name__) for a in array_type]
array_type_print
", ".join(array_type_print)

'ndarray, list, tuple'

In [13]:
def func(x : string_type) -> string_type:
    return x