In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt


plt.rcParams.update({
    "text.usetex": True,
    "font.family": "Helvetica"
})

import matplotlib as mpl

In [2]:
import sys
from os.path import dirname

sys.path.append(dirname("../src/"))

import samosa.symmetry.symmetry_utils as symmetry
import samosa.symmetry.point_group_utils as pg_utils

In [3]:
p = symmetry.PermutationGroupElement({0:1,1:2,2:0})

In [4]:
type(None)

NoneType

In [5]:
p = symmetry.PermutationGroupElement((1,2,0))
p

PermutationGroupElement(permutation = (1, 2, 0))

In [6]:
issubclass(p.__class__,symmetry.GroupElement)

True

In [7]:
p * (0,1,2)

(1, 2, 0)

In [8]:
isinstance(np.zeros(3),np.ndarray)

True

In [9]:
p.inv()

PermutationGroupElement(permutation = (2, 0, 1))

In [10]:
pg_test = pg_utils.point_group('C4v')

In [11]:
isinstance(pg_test,symmetry.GroupElement)

False

In [12]:
test_o,test_g,test_t,test_s = pg_test.calculate_orbit([1,0,0],as_pointer=True)

In [13]:
test_o

[array([1, 0, 0]),
 array([0., 1., 0.]),
 array([-1.,  0.,  0.]),
 array([ 0., -1.,  0.])]

In [14]:
test_g

[PermutationGroupElement(permutation = (1, 2, 3, 0)),
 PermutationGroupElement(permutation = (0, 3, 2, 1))]

In [15]:
test_t

{(1, 0, 0): PointerGroupElement(pointer = []),
 (0.0, 1.0, 0.0): PointerGroupElement(pointer = [(0, 1)]),
 (-1.0, 0.0, 0.0): PointerGroupElement(pointer = [(0, 2)]),
 (0.0, -1.0, 0.0): PointerGroupElement(pointer = [(1, 1), (0, 1)])}

In [16]:
test_s

[PointerGroupElement(pointer = []),
 PointerGroupElement(pointer = [(1, 1)]),
 PointerGroupElement(pointer = [(1, 1), (0, 2)]),
 PointerGroupElement(pointer = [(0, 2), (1, 1), (0, 2)]),
 PointerGroupElement(pointer = [(0, 1), (1, 1), (0, 1)])]

In [17]:
test_s[1]*test_s[1]

PointerGroupElement(pointer = [])

In [13]:
tuple(np.arange(6))

(0, 1, 2, 3, 4, 5)

In [22]:
pg_test.generators += [pg_test.generators[0]*pg_test.generators[1]]
pg_test.generators

[MatrixGroupElement(operator = array([[ 0., -1.,  0.],
        [ 1.,  0.,  0.],
        [ 0.,  0.,  1.]])),
 MatrixGroupElement(operator = array([[ 1., -0., -0.],
        [-0., -1., -0.],
        [ 0., -0.,  1.]])),
 MatrixGroupElement(operator = array([[0., 1., 0.],
        [1., 0., 0.],
        [0., 0., 1.]])),
 MatrixGroupElement(operator = array([[0., 1., 0.],
        [1., 0., 0.],
        [0., 0., 1.]]))]

In [23]:
pg_test.generator_filter()

In [24]:
pg_test.generators

[MatrixGroupElement(operator = array([[ 0., -1.,  0.],
        [ 1.,  0.,  0.],
        [ 0.,  0.,  1.]])),
 MatrixGroupElement(operator = array([[ 1., -0., -0.],
        [-0., -1., -0.],
        [ 0., -0.,  1.]]))]

In [29]:
test_s[-1]

PointerGroupElement(pointer = [(0, 3), (0, 1)])

In [26]:
array_type = (np.ndarray,list,tuple)
array_type_print = [str(a.__name__) for a in array_type]
array_type_print
", ".join(array_type_print)

'ndarray, list, tuple'

In [13]:
def func(x : string_type) -> string_type:
    return x