In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import sympy as sp
sp.init_printing()

plt.rcParams.update({
    "text.usetex": True,
    "font.family": "Helvetica"
})

import matplotlib as mpl

In [2]:
import sys
from os.path import dirname
sys.path.append(dirname("/home/azelenskiy/Documents/Numerics/"\
                      + "frusa_symmetry/python/src/"))
import symmetry_utils as symmetry

In [14]:
x,y,z = sp.symbols('x y z')

In [23]:
#Initialize generator sets for a given point group

test_generators_symbols = symmetry.point_group_lib['D6h']['generators']
test_generators_operators = [symmetry.get_symmetry_matrix(s) \
                             for s in test_generators_symbols]
test_generators_symbols

['C3p_H,001', 'C2,001', 'C2,110', 'I,000']

In [32]:
# Calculate orbit, transporters, and generators of the stabilizer group
test_o, test_t, test_s = symmetry.point_transform(np.array([1,0,0]), test_generators_operators)

In [33]:
test_o

[array([1, 0, 0]),
 array([0, 1, 0]),
 array([-1,  0,  0]),
 array([-1, -1,  0]),
 array([ 0, -1,  0]),
 array([1, 1, 0])]

In [34]:
# Check that the transporter elements produce the full orbit by acting on the 
# first 'seed' point
for p in test_o:
    print(test_t[tuple(p)].dot(test_o[0]))

[1 0 0]
[0 1 0]
[-1  0  0]
[-1 -1  0]
[ 0 -1  0]
[1 1 0]


In [35]:
# Verify the stabilizers of the point
[symmetry.get_symmetry_symbol(s) for s in test_s]

['C2_H,100', 'm,001']

In [38]:
symmetry.point_transform(np.array([0,y,0]), test_s)

([array([0, y, 0], dtype=object), array([-y, -y, 0], dtype=object)],
 {(0,
   y,
   0): array([[1, 0, 0],
         [0, 1, 0],
         [0, 0, 1]]),
  (-y,
   -y,
   0): array([[ 1, -1,  0],
         [ 0, -1,  0],
         [ 0,  0, -1]])},
 [array([[ 1,  0,  0],
         [ 0,  1,  0],
         [ 0,  0, -1]])])

In [22]:
symmetry.permutation_representation(test_o, test_t[tuple(test_o[3])])