In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

plt.rcParams.update({
    "text.usetex": True,
    "font.family": "Helvetica"
})

import matplotlib as mpl

In [2]:
import sys
from os.path import dirname
sys.path.append(dirname("/home/azelenskiy/Documents/Numerics/"\
                      + "frusa_symmetry/python/src/"))
import symmetry_utils as symmetry

## Tools for symmetry operations

__Desired properties:__

* Relating operator names to matrix operations
* Identification of orbits
* Constructing stabilizer groups

In [11]:
# Print the point group lookup library
symmetry.point_group_lib

{'C1': {'generators': ['E,000']},
 'Ci': {'generators': ['I,000']},
 'C2': {'generators': ['C2,001']},
 'Cs': {'generators': ['m,001']},
 'C2h': {'generators': ['C2,001', 'I,000']},
 'D2': {'generators': ['C2,010', 'C2,001']},
 'C2v': {'generators': ['C2,001', 'm,010']},
 'D2h': {'generators': ['C2,010', 'C2,001', 'I,000']},
 'C4': {'generators': ['C4p,001']},
 'S4': {'generators': ['S4p,001']},
 'C4h': {'generators': ['C4p,001', 'I,000']},
 'D4': {'generators': ['C4p,001', 'C2,010', 'C2,001']},
 'C4v': {'generators': ['C4p,001', 'C2,001', 'm,010']},
 'D2d': {'generators': ['S4p,001', 'C2,010', 'C2,001']},
 'D4h': {'generators': ['C4p,001', 'C2,010', 'C2,001', 'I,000']},
 'C3': {'generators': ['C3p,001']},
 'C3i': {'generators': ['S3p,001']},
 'D3': {'generators': ['C3p,001', 'C2,1-10']},
 'C3v': {'generators': ['C3p,001', 'm,110']},
 'D3d': {'generators': ['S6p,001', 'C2,1-10', 'I,000']},
 'C6': {'generators': ['C6p_H,001']},
 'C3h': {'generators': ['C3p_H,001', 'I,000']},
 'C6h': {'g

In [12]:
#Initialize generator sets for a given point group

test_generators_symbols = symmetry.point_group_lib['D6']['generators']
test_generators_operators = [symmetry.get_symmetry_matrix(s) \
                             for s in test_generators_symbols]
test_generators_symbols

['C3p_H,001', 'C2,001', 'C2,110']

In [13]:
# Calculate orbit, transporters, and generators of the stabilizer group
test_o, test_t, test_s = symmetry.point_transform(np.array([1,0,0]), test_generators_operators)

In [14]:
test_o

[array([1, 0, 0]),
 array([0, 1, 0]),
 array([-1,  0,  0]),
 array([-1, -1,  0]),
 array([ 0, -1,  0]),
 array([1, 1, 0])]

In [16]:
# Check that the transporter elements produce the full orbit by acting on the 
# first 'seed' point
for p in test_o:
    print(test_t[tuple(p)].dot(test_o[0]))

[1 0 0]
[0 1 0]
[-1  0  0]
[-1 -1  0]
[ 0 -1  0]
[1 1 0]


In [19]:
# Verify the stabilizers of the point
[symmetry.get_symmetry_symbol(s) for s in test_s]

['C2_H,100']