In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt


plt.rcParams.update({
    "text.usetex": True,
    "font.family": "Helvetica"
})

import matplotlib as mpl

In [2]:
import sys
from os.path import dirname
sys.path.append(dirname("/home/azelenskiy/Documents/"\
                      + "frusa_symmetry/python/src/symmetry/"))
import symmetry_utils as symmetry
import point_group_utils as pg_utils

In [3]:
'C3v'[2]

'v'

In [4]:
pg_utils.point_group('C3v').

In [5]:
len(None)

TypeError: object of type 'NoneType' has no len()

In [10]:
test_operator = pg_utils.operator_C([1,0,0],4)
test_operator

array([[ 1.000000e+00,  0.000000e+00,  0.000000e+00],
       [ 0.000000e+00,  6.123234e-17, -1.000000e+00],
       [ 0.000000e+00,  1.000000e+00,  6.123234e-17]])

In [4]:
pg_utils.operator_to_symbol(test_operator)

'C4,100'

In [5]:
test_element = pg_utils.matrix_group_element(test_operator)
print(test_element)

[[ 1.  0.  0.]
 [ 0.  0. -1.]
 [ 0.  1.  0.]]


In [6]:
test_element.operator_inv

In [7]:
[0,1,0]*test_element

array([ 0.000000e+00,  6.123234e-17, -1.000000e+00])

In [36]:
test_element*(0,1,0)

AttributeError: 'matrix_group_element' object has no attribute '__name__'

In [15]:
print(symmetry.group([test_element]))

Symmetry group defined by generators:
[[ 1.  0.  0.]
 [ 0.  0. -1.]
 [ 0.  1.  0.]]


In [34]:
np.isclose(np.random.uniform(-1e-8,1e-7,(3,3)),0,10).all()

False

In [44]:
a_list = [(np.random.randint(5),np.random.randint(5)) for i in range(10)]
a_list

[(2, 3),
 (3, 2),
 (0, 4),
 (0, 1),
 (1, 2),
 (0, 4),
 (3, 3),
 (4, 0),
 (3, 0),
 (3, 2)]

In [48]:
a_list==a_list

True

In [15]:
test_list = [np.random.uniform(-1,1,(3,3)),np.random.uniform(-1,1,(3,3))]

test_list_str = [str(a) for a in test_list]

print("\n\n".join(test_list_str))

[[ 0.81020987  0.53957486 -0.4909054 ]
 [ 0.71760914 -0.77111446 -0.43767551]
 [-0.65124744 -0.72467514  0.53580906]]

[[ 0.23442222  0.69186753 -0.13591546]
 [-0.95113441 -0.68614261  0.4375854 ]
 [-0.19284628 -0.69695293 -0.76797398]]


In [3]:
test_operator = symmetry.operator_M(np.array([0,1,1.]))
test_operator

array([[ 1.00000000e+00,  8.65956056e-17, -8.65956056e-17],
       [-8.65956056e-17,  2.22044605e-16, -1.00000000e+00],
       [ 8.65956056e-17, -1.00000000e+00,  2.22044605e-16]])

In [4]:
symmetry.operator_to_symbol(test_operator)

'M,0-1-1'

In [6]:
symmetry.symbol_to_operator("T2,110")

ValueError: Incorrect symmetry symbol: T2,110

In [3]:
# Print the point group lookup library
symmetry.point_group_lib

{'C1': {'generators': ['E,000']},
 'Ci': {'generators': ['I,000']},
 'C2': {'generators': ['C2,001']},
 'Cs': {'generators': ['m,001']},
 'C2h': {'generators': ['C2,001', 'I,000']},
 'D2': {'generators': ['C2,010', 'C2,001']},
 'C2v': {'generators': ['C2,001', 'm,010']},
 'D2h': {'generators': ['C2,010', 'C2,001', 'I,000']},
 'C4': {'generators': ['C4p,001']},
 'S4': {'generators': ['S4p,001']},
 'C4h': {'generators': ['C4p,001', 'I,000']},
 'D4': {'generators': ['C4p,001', 'C2,010', 'C2,001']},
 'C4v': {'generators': ['C4p,001', 'C2,001', 'm,010']},
 'D2d': {'generators': ['S4p,001', 'C2,010', 'C2,001']},
 'D4h': {'generators': ['C4p,001', 'C2,010', 'C2,001', 'I,000']},
 'C3': {'generators': ['C3p,001']},
 'C3i': {'generators': ['S3p,001']},
 'D3': {'generators': ['C3p,001', 'C2,1-10']},
 'C3v': {'generators': ['C3p,001', 'm,110']},
 'D3d': {'generators': ['S6p,001', 'C2,1-10', 'I,000']},
 'C6': {'generators': ['C6p_H,001']},
 'C3h': {'generators': ['C3p_H,001', 'I,000']},
 'C6h': {'g

In [4]:
#Initialize generator sets for a given point group

test_generators_symbols = symmetry.point_group_lib['D6']['generators']
test_generators_operators = [symmetry.get_symmetry_matrix(s) \
                             for s in test_generators_symbols]
test_generators_symbols

['C3p_H,001', 'C2,001', 'C2,110']

In [5]:
# Calculate orbit, transporters, and generators of the stabilizer group
test_o, test_t, test_s = symmetry.point_transform(np.array([1,0,0]), test_generators_operators)

In [6]:
test_o

[array([1, 0, 0]),
 array([0, 1, 0]),
 array([-1,  0,  0]),
 array([-1, -1,  0]),
 array([ 0, -1,  0]),
 array([1, 1, 0])]

In [7]:
# Check that the transporter elements produce the full orbit by acting on the 
# first 'seed' point
for p in test_o:
    print(test_t[tuple(p)].dot(test_o[0]))

[1 0 0]
[0 1 0]
[-1  0  0]
[-1 -1  0]
[ 0 -1  0]
[1 1 0]


In [8]:
# Verify the stabilizers of the point
[symmetry.get_symmetry_symbol(s) for s in test_s]

['C2_H,100']